
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
server:
  port: 8080
# Routes will be discovered from Eureka; e.g., http://localhost:8080/payment-service/payments/charge
